### ISSUE TITLE
Security Labs

### ISSUE THREAD

**Issue by foxgarden** [foxgarden/SEBC#6]

**Comment by foxgarden** [comment]
Integrating Kerberos with Cloudera Manager

Should NOT choose CM to manage krb5.conf file. If select that checkbox, CM will overwrite current krb5.conf file, and the new file is not correct, which lead a mistake when starting services.

**Comment by foxgarden** [comment]
done

**Comment by mfernest** [comment]
`kinit.md` - note you have a non-renewing ticket: the initial and renewable timestamps are equal.
